pipeline:
  name: newJenkins
  identifier: newJenkins
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: jhhtpconnector
        build: <+input>
  stages:
    - stage:
        name: testbuild
        identifier: testbuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: dockerconnector
                    image: test
                    shell: Sh
                    command: echo Hello
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerconnector
                    repo: test
                    tags:
                      - newdefault
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
    - stage:
        name: jenkinsdeploy
        identifier: jenkinsdeploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: testjenkins
          environment:
            environmentRef: testproduction
            deployToAll: false
            infrastructureDefinitions:
              - identifier: test
          execution:
            steps:
              - step:
                  type: JenkinsBuild
                  name: JenkinsBuild_1
                  identifier: JenkinsBuild_1
                  spec:
                    connectorRef: newjenkinsconnector
                    jobName: jhhtp
                    jobParameter: []
                    unstableStatusAsSuccess: true
                    useConnectorUrlForJobExecution: false
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        delegateSelectors:
          - firstk8sdel
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: ManualIntervention
                spec:
                  timeout: 10m
                  onTimeout:
                    action:
                      type: Ignore
